### PR TITLE
Backwards nim compat, more examples, and `check` update

### PR DESCRIPTION
**Pull request by lilkeet**
this pr:
- fixes issue #21 
- adds three new examples/tests added (issue #19)
- changes `check` template to a func (a97a1ea974ef78dd9e20da00e66a6c22f6739e88)
- ensures library is compatible with nim >= 1.4.0

### CODE REVIEW

**Review by Clonkk — APPROVED** [review]
Nice clean-up !

**Comment by Clonkk** [comment]
unrelated to tour PR, but we should really setup CI for nimcuda

**Comment by Clonkk** [comment]
@Vindaar waiting for you to have a look, will merge tomorrow or Tuesday

**Comment by lilkeet** [comment]
> unrelated to tour PR, but we should really setup CI for nimcuda

agreed, had the same thought as i was makin this pr lol

**Comment by Vindaar** [comment]
Nice, thanks!

**Pull request merged**
